// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkfvhjDTmjx4vKe4ZoKMNdYUJNZORlGe4',
    appId: '1:863614776368:web:756fd8f40bef7f79a2a9f5',
    messagingSenderId: '863614776368',
    projectId: 'bgt-gorevler',
    authDomain: 'bgt-gorevler.firebaseapp.com',
    storageBucket: 'bgt-gorevler.firebasestorage.app',
    measurementId: 'G-6SXQRJEP5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCgZ8oUChevDvP6KbpjkpmI4qp7SY5Gw0',
    appId: '1:863614776368:android:c1c3f45ba35ffdc9a2a9f5',
    messagingSenderId: '863614776368',
    projectId: 'bgt-gorevler',
    storageBucket: 'bgt-gorevler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ4NIlLEhQU1-Auz6EamH_wsR8oTbyo3o',
    appId: '1:863614776368:ios:81fd6788b464dceda2a9f5',
    messagingSenderId: '863614776368',
    projectId: 'bgt-gorevler',
    storageBucket: 'bgt-gorevler.firebasestorage.app',
    iosBundleId: 'com.bgt.gorevler',
  );
}
